### ISSUE TITLE
associating PV to jupyter notebook

### ISSUE THREAD

**Issue by dbrrt** [GrahamDumpleton/openshift3-jupyter-notebook#1]
Is that possible to mount Jupyter data to a persistent volume to avoid data loss when container restarts?

**Comment by GrahamDumpleton** [comment]
Go to:

* https://blog.openshift.com/jupyter-on-openshift-part-7-adding-the-image-to-the-catalog/

Go to the bottom of the post and read parts 1-6 and then that final part 7.

It goes through various issues including using persistent storage.

This particular repo is an earlier experiment. I should work out whether I should delete it in favour of others.

**Comment by dbrrt** [comment]
Thanks a lot for your work on Openshift and your documentation.
I found what I needed there :  https://blog.openshift.com/jupyter-on-openshift-part-4-adding-a-persistent-workspace/
